// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3Zgjyw9Jz8AEHZdA87FKYvdBNk7pfWEA',
    appId: '1:272453477913:web:8b9a796e3b62a0aec7ac88',
    messagingSenderId: '272453477913',
    projectId: 'geofaunagps',
    authDomain: 'geofaunagps.firebaseapp.com',
    storageBucket: 'geofaunagps.firebasestorage.app',
    measurementId: 'G-K9EZG8EQVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmdoKtvV0-wJQns8UBP8S1vWaDpqUhj70',
    appId: '1:272453477913:android:69b17445a50eec93c7ac88',
    messagingSenderId: '272453477913',
    projectId: 'geofaunagps',
    storageBucket: 'geofaunagps.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI-GfoYJ37CO5qerGLcUh2sU0VXBX3xtE',
    appId: '1:272453477913:ios:7745b6d7e9d9c769c7ac88',
    messagingSenderId: '272453477913',
    projectId: 'geofaunagps',
    storageBucket: 'geofaunagps.firebasestorage.app',
    iosBundleId: 'com.example.geofauna',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3Zgjyw9Jz8AEHZdA87FKYvdBNk7pfWEA',
    appId: '1:272453477913:web:578717602a5eb51bc7ac88',
    messagingSenderId: '272453477913',
    projectId: 'geofaunagps',
    authDomain: 'geofaunagps.firebaseapp.com',
    storageBucket: 'geofaunagps.firebasestorage.app',
    measurementId: 'G-1EY9F8DLMX',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI-GfoYJ37CO5qerGLcUh2sU0VXBX3xtE',
    appId: '1:272453477913:ios:4bb594b7a29f11c2c7ac88',
    messagingSenderId: '272453477913',
    projectId: 'geofaunagps',
    storageBucket: 'geofaunagps.firebasestorage.app',
    iosBundleId: 'com.geofauna.app',
  );

}